site_url: https://moritz-john.github.io/kmk-config-splaytoraid
repo_url: https://github.com/moritz-john/kmk-config-splaytoraid

site_name: Splaytoraid KMK Documentation
theme:
  custom_dir: docs/overrides
  name: material
  palette:
    scheme: slate
    primary: black
    accent: green
  logo: assets/logo.svg
  favicon: assets/favicon.png
  # Change default github repository icon, top right
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  # Images:
  - attr_list
  - md_in_html
  # Code:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Admonitions:
  - admonition
  - pymdownx.details
  # Tables:
  - tables
  # Footnoes:
  - footnotes
  # Keys:
  - pymdownx.keys:
      key_map: {
                "rgbtog": "KC.RGB_TOG", 
                "rgbhui": "KC.RGB_HUI",
                "rgbhud": "KC.RGB_HUD",
                "rgbsai": "KC.RGB_SAI",
                "rgbsad": "KC.RGB_SAD",
                "rgbvai": "KC.RGB_VAI",
                "rgbvad": "KC.RGB_VAD",
               }

# Social cards
plugins:
  - social

# Footer: social links
extra:
  social:
    - icon: fontawesome/solid/basket-shopping
      link: https://keeb.supply/products/splaytoraid-messenger-edition
      name: Buy yourself a splaytoraid
    - icon: fontawesome/brands/github
      link: https://github.com/moritz-john/
      name: moritz-john Github

copyright: Created and maintained by Moritz John